### PR TITLE
Implement Db cluster CRUD

### PR DESCRIPTION
**Pull request by amazzalel-habib**
This PR implements basic db cluster crud operations.

### CODE REVIEW

**Comment by liskl** [comment]
seeing an error in the tests
```
liskl@DESKTOP-D9PIEKG:~/k8s-rds$ git checkout db-cluster
branch 'db-cluster' set up to track 'origin/db-cluster'.
Switched to a new branch 'db-cluster'
liskl@DESKTOP-D9PIEKG:~/k8s-rds$ git ffwd-update
Fetching origin
 branch restore-from-snapshot was 1 commit(s) behind of origin/restore-from-snapshot. reseting local branch to remote
liskl@DESKTOP-D9PIEKG:~/k8s-rds$ make docker-push
docker build --load -t liskl/k8s-rds:db-cluster-1663267453 .
[+] Building 58.0s (16/18)
 => [internal] booting buildkit                                                                                                                        1.4s
 => => starting container buildx_buildkit_competent_haibt0                                                                                             1.4s
 => [internal] load build definition from Dockerfile                                                                                                   0.0s
 => => transferring dockerfile: 384B                                                                                                                   0.0s
 => [internal] load .dockerignore                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                        0.0s
 => [internal] load metadata for docker.io/library/alpine:latest                                                                                       2.0s
 => [internal] load metadata for docker.io/library/golang:1.17.0-alpine                                                                                2.1s
 => [auth] library/golang:pull token for registry-1.docker.io                                                                                          0.0s
 => [auth] library/alpine:pull token for registry-1.docker.io                                                                                          0.0s
 => [builder 1/7] FROM docker.io/library/golang:1.17.0-alpine@sha256:c03a922dfb0d6d3a94d46cc5be69002011763595ac2786068fde63ee174d797b                  0.0s
 => => resolve docker.io/library/golang:1.17.0-alpine@sha256:c03a922dfb0d6d3a94d46cc5be69002011763595ac2786068fde63ee174d797b                          0.0s
 => [internal] load build context                                                                                                                      0.0s
 => => transferring context: 408.38kB                                                                                                                  0.0s
 => [stage-1 1/3] FROM docker.io/library/alpine@sha256:bc41182d7ef5ffc53a40b044e725193bc10142a1243f395ee852a8d9730fc2ad                                0.0s
 => => resolve docker.io/library/alpine@sha256:bc41182d7ef5ffc53a40b044e725193bc10142a1243f395ee852a8d9730fc2ad                                        0.0s
 => CACHED [builder 2/7] WORKDIR /app                                                                                                                  0.0s
 => CACHED [builder 3/7] RUN apk --no-cache add git make                                                                                               0.0s
 => [builder 4/7] COPY Makefile go.mod go.sum ./                                                                                                       0.1s
 => [builder 5/7] RUN make mod tools                                                                                                                  38.7s
 => [builder 6/7] COPY . .                                                                                                                             0.6s
 => ERROR [builder 7/7] RUN make test lint build                                                                                                      15.0s
------
 > [builder 7/7] RUN make test lint build:
#0 0.111 CGO_ENABLED=0 go test ./... -v
#0 13.32 # github.com/sorenmat/k8s-rds [github.com/sorenmat/k8s-rds.test]
#0 13.32 ./main_test.go:53:25: not enough arguments in call to excluded
#0 13.32        have (*crd.Database, []string, []string)
#0 13.32        want (string, string, []string, []string)
#0 13.32 note: module requires Go 1.18
#0 14.51 FAIL   github.com/sorenmat/k8s-rds [build failed]
#0 14.51 ?      github.com/sorenmat/k8s-rds/client      [no test files]
#0 14.51 === RUN   TestMarshal
#0 14.51 apiVersion: k8s-rds.io/v1
#0 14.51 kind: Database
#0 14.51 metadata:
#0 14.51   creationTimestamp: null
#0 14.51   name: my_db
#0 14.51   namespace: default
#0 14.51 spec:
#0 14.51   MaxAllocatedSize: 20
#0 14.51   backupretentionperiod: 10
#0 14.51   class: db.t2.micro
#0 14.51   dbname: database_name
#0 14.51   encrypted: true
#0 14.51   engine: postgres
#0 14.51   multiaz: true
#0 14.51   password:
#0 14.51     key: key
#0 14.51     name: DB-Secret
#0 14.51   provider: local
#0 14.51   size: 20
#0 14.51   storagetype: gp2
#0 14.51   username: dbuser
#0 14.51   version: ""
#0 14.51 status: {}
#0 14.51
#0 14.51 --- PASS: TestMarshal (0.00s)
#0 14.51 === RUN   TestCRDValidationWithValidInput
#0 14.51 --- PASS: TestCRDValidationWithValidInput (0.00s)
#0 14.51 === RUN   TestCaseInsensitiveInput
#0 14.51 --- PASS: TestCaseInsensitiveInput (0.00s)
#0 14.51 === RUN   TestDatabaseSizeIsTooSmall
#0 14.51 --- PASS: TestDatabaseSizeIsTooSmall (0.00s)
#0 14.51 === RUN   TestDatabaseSizeIsTooBig
#0 14.51 --- PASS: TestDatabaseSizeIsTooBig (0.00s)
#0 14.51 === RUN   TestBackupRetentionPeriodIsTooLong
#0 14.51 --- PASS: TestBackupRetentionPeriodIsTooLong (0.01s)
#0 14.51 === RUN   TestInvalidDatabaseNameWithDashSeparator
#0 14.51 --- PASS: TestInvalidDatabaseNameWithDashSeparator (0.00s)
#0 14.51 === RUN   TestInvalidDatabaseNameStartingWithANumber
#0 14.51 --- PASS: TestInvalidDatabaseNameStartingWithANumber (0.00s)
#0 14.51 === RUN   TestInvalidUsername
#0 14.51 --- PASS: TestInvalidUsername (0.00s)
#0 14.51 === RUN   TestInvalidStorageType
#0 14.51 --- PASS: TestInvalidStorageType (0.00s)
#0 14.51 === RUN   TestIopsTooSmall
#0 14.51 --- PASS: TestIopsTooSmall (0.00s)
#0 14.51 === RUN   TestIopsTooBig
#0 14.51 --- PASS: TestIopsTooBig (0.00s)
#0 14.51 PASS
#0 14.51 ok     github.com/sorenmat/k8s-rds/crd 0.048s
#0 14.51 ?      github.com/sorenmat/k8s-rds/kube        [no test files]
#0 14.51 === RUN   TestConvertSpecToDeployment
#0 14.51 --- PASS: TestConvertSpecToDeployment (0.00s)
#0 14.51 === RUN   TestCreateDatabase
#0 14.51 2022/09/15 18:45:06 creating pvc mydb
#0 14.51 2022/09/15 18:45:06 creating database mydb
#0 14.51 --- PASS: TestCreateDatabase (0.00s)
#0 14.51 === RUN   TestUpdateDatabase
#0 14.51 2022/09/15 18:45:06 creating pvc mydb
#0 14.51 2022/09/15 18:45:06 creating database mydb
#0 14.51 2022/09/15 18:45:06 updating pvc mydb
#0 14.51 2022/09/15 18:45:06 Specs mydb has same size: not updating pvc
#0 14.51 2022/09/15 18:45:06 updating database mydb
#0 14.51 --- PASS: TestUpdateDatabase (0.00s)
#0 14.51 PASS
#0 14.51 ok     github.com/sorenmat/k8s-rds/local       0.009s
#0 14.51 ?      github.com/sorenmat/k8s-rds/provider    [no test files]
#0 14.52 === RUN   TestConvertSpecToInput
#0 14.52 --- PASS: TestConvertSpecToInput (0.00s)
#0 14.52 === RUN   TestGetIDFromProvider
#0 14.52 --- PASS: TestGetIDFromProvider (0.00s)
#0 14.52 === RUN   TestToTags
#0 14.52 2022/09/15 18:45:11 WARNING: Not Adding annotation KV to tags: kubectl-key2-test test-value
#0 14.52 2022/09/15 18:45:11 WARNING: Not Adding annotation KV to tags: annotation-key1-test banjmdvgeezuadqvehvqaxxmzwykirejkwvktkxmvjdevcfhqootqyfdfvqatjiebglktdswnvzxcpnstvrurpfjfuxhsjvgogrnhazjizakttdncmjnbofvwcsccigfcyxzlunfndcjteuqmjpslqvefvobfnejjxtwbyrkcvsvqokkrskrryzbhhayegyuwhugyorkltmsipvznxkonqzzwihjdejqgzfjivjdqmieidkowryfjnnyrxszsyhnpfeepxyoliskexxpjtxn
#0 14.52 2022/09/15 18:45:11 WARNING: Not Adding annotation KV to tags: kubectl-key2-test test-value
#0 14.52 2022/09/15 18:45:11 WARNING: Not Adding CRD labels KV to tags: label-key2-test banjmdvgeezuadqvehvqaxxmzwykirejkwvktkxmvjdevcfhqootqyfdfvqatjiebglktdswnvzxcpnstvrurpfjfuxhsjvgogrnhazjizakttdncmjnbofvwcsccigfcyxzlunfndcjteuqmjpslqvefvobfnejjxtwbyrkcvsvqokkrskrryzbhhayegyuwhugyorkltmsipvznxkonqzzwihjdejqgzfjivjdqmieidkowryfjnnyrxszsyhnpfeepxyoliskexxpjtxn
#0 14.52 --- PASS: TestToTags (0.00s)
#0 14.52 === RUN   TestTags
#0 14.52 --- PASS: TestTags (0.00s)
#0 14.52 === RUN   TestTagsWithSpaces
#0 14.52 --- PASS: TestTagsWithSpaces (0.00s)
#0 14.52 === RUN   TestConvertSpecToDeleteInput_enabled
#0 14.52 --- PASS: TestConvertSpecToDeleteInput_enabled (0.00s)
#0 14.52 === RUN   TestConvertSpecToDeleteInput_disabled
#0 14.52 --- PASS: TestConvertSpecToDeleteInput_disabled (0.00s)
#0 14.52 === RUN   TestConvertSpecToModifyInput_withApplyImmediately
#0 14.52 --- PASS: TestConvertSpecToModifyInput_withApplyImmediately (0.00s)
#0 14.52 === RUN   TestConvertSpecToModifyInput_withoutApplyImmediately
#0 14.52 --- PASS: TestConvertSpecToModifyInput_withoutApplyImmediately (0.00s)
#0 14.52 === RUN   TestConvertSpecToRestoreFromSnapshotInput
#0 14.52 --- PASS: TestConvertSpecToRestoreFromSnapshotInput (0.00s)
#0 14.52 PASS
#0 14.52 ok     github.com/sorenmat/k8s-rds/rds 0.005s
#0 14.52 FAIL
#0 14.59 make: *** [Makefile:17: test] Error 2
------
Dockerfile:10
--------------------
   8 |
   9 |     COPY . .
  10 | >>> RUN make test lint build
  11 |
  12 |     FROM alpine
--------------------
error: failed to solve: process "/bin/sh -c make test lint build" did not complete successfully: exit code: 2
make: *** [Makefile:24: docker-build] Error 1
```

**Comment by amazzalel-habib** [comment]
> 

weird, it's working fine locally

**Comment by liskl** [comment]
just made one message regarding requiring go 1.18 disappear, but still that test is failing and it appears to be related to wrong number of arguments.

```
liskl@DESKTOP-D9PIEKG:~/k8s-rds$ CGO_ENABLED=0 go test ./... -v
# github.com/sorenmat/k8s-rds [github.com/sorenmat/k8s-rds.test]
./main_test.go:53:48: not enough arguments in call to excluded
        have (*crd.Database, []string, []string)
        want (string, string, []string, []string)
FAIL    github.com/sorenmat/k8s-rds [build failed]
```

**Comment by liskl** [comment]
can you give the output of `make docker-tag` from your end @amazzalel-habib ?

**Comment by amazzalel-habib** [comment]
> just made one message regarding requiring go 1.18 disappear, but still that test is failing and it appears to be related to wrong number of arguments.
> 
> ```
> liskl@DESKTOP-D9PIEKG:~/k8s-rds$ CGO_ENABLED=0 go test ./... -v
> # github.com/sorenmat/k8s-rds [github.com/sorenmat/k8s-rds.test]
> ./main_test.go:53:48: not enough arguments in call to excluded
>         have (*crd.Database, []string, []string)
>         want (string, string, []string, []string)
> FAIL    github.com/sorenmat/k8s-rds [build failed]
> ```

could it be the cache? because if you check `main_test.go:53:48`, it has the signature `(string, string, []string, []string)` not `(*crd.Database, []string, []string)`

**Comment by liskl** [comment]
Line 53 shows
```
                        if actual := excluded(test.db, test.exclNS, test.inclNS); actual != expected {
```

That is only three arguments. On your branch.

**Comment by liskl** [comment]
image builds now will test functionality shortly.

**Comment by liskl** [comment]
so created and deleting the database cluster object works, with no instances inside as expected with the CRUD, but there is a ModifyCluster happening right after as decribed here when the cluster is still in the creating state

```
2022/09/16 16:55:04 Seems like we are running in a Kubernetes cluster!!
2022/09/16 16:55:04 services "pgsql-cluster-1" not found
2022/09/16 16:55:04 delete of service pgsql-cluster-1 failed in namespace rds-operator: services "pgsql-cluster-1" not found
2022/09/16 16:55:04 Deletion of db cluster pgsql-cluster-1 done
2022/09/16 16:55:23 New resource version of the DB cluster pgsql-cluster-1 is 736737428
2022/09/16 16:55:23 trying to get kubectl
2022/09/16 16:55:23 Seems like we are running in a Kubernetes cluster!!
2022/09/16 16:55:23 Found node with ID: i-04b6432d9ebeb2e3b in region us-west-2
2022/09/16 16:55:24 Taking subnets from node i-04b6432d9ebeb2e3b
2022/09/16 16:55:24 trying to describe instance
2022/09/16 16:55:27 trying to get subnets
2022/09/16 16:55:27 Security groupid:  sg-0f3ce7d47d2175a68
2022/09/16 16:55:27 Found VPC vpc-0fdfd77cda33f681c will search for subnet in that VPC
2022/09/16 16:55:27 Found the follwing subnets:
2022/09/16 16:55:27 subnet-0312bd982d89f088e
2022/09/16 16:55:27 subnet-0791eebb4d3e05f81
2022/09/16 16:55:27 subnet-0d97c4fef202c5aae
2022/09/16 16:55:27 subnet-07982cc3f1c41d778
2022/09/16 16:55:27 subnet-067c1fbeb25342eb7
2022/09/16 16:55:27 subnet-091d17ae01b066f88
2022/09/16 16:55:27 trying to get security groups
2022/09/16 16:55:27 Taking security groups from node i-04b6432d9ebeb2e3b
2022/09/16 16:55:27 trying to describe instance
2022/09/16 16:55:27 got instance response
2022/09/16 16:55:27 Security groupid:  sg-0f3ce7d47d2175a68
2022/09/16 16:55:27 Found the follwing security groups:
2022/09/16 16:55:27 sg-0f3ce7d47d2175a68
2022/09/16 16:55:27 Trying to find the correct subnets
2022/09/16 16:55:28 Subnets: [subnet-0312bd982d89f088e subnet-0791eebb4d3e05f81 subnet-0d97c4fef202c5aae subnet-07982cc3f1c41d778 subnet-067c1fbeb25342eb7 subnet-091d17ae01b066f88]
2022/09/16 16:55:28 Moving on seems like db-subnetgroup-vpc-0fdfd77cda33f681c exsits
2022/09/16 16:55:28 getting secret: Name: rds-credentials Key: password
2022/09/16 16:55:28 Seems like we are running in a Kubernetes cluster!!
2022/09/16 16:55:28 WARNING: Not Adding annotation KV to tags: kubectl.kubernetes.io/last-applied-configuration {"apiVersion":"k8s-rds.io/v1","kind":"DBCluster","metadata":{"annotations":{},"name":"pgsql-cluster-1","namespace":"rds-operator"},"spec":{"BackupRetentionPeriod":1,"DBClusterIdentifier":"pgsql-cluster-junk","DeletionProtection":false,"Engine":"aurora-postgresql","EngineVersion":"14.3","MasterUserPassword":{"key":"password","name":"rds-credentials"},"MasterUsername":"postgres","MultiAZ":false,"Port":5432,"Provider":"aws","ServerlessV2ScalingConfiguration":{"MaxCapacity":11,"MinCapacity":1},"SkipFinalSnapshot":true,"Tags":"key=value,key1=value1"}}
2022/09/16 16:55:28 Trying to find db cluster pgsql-cluster-junk
2022/09/16 16:55:28 DB Cluster instance 0xc00081a660 not found trying to create it
2022/09/16 16:55:30 Waiting for db cluster instance with ID pgsql-cluster-junk  to become available
2022/09/16 16:56:15 DB cluster pgsql-cluster-junk is now available
2022/09/16 16:56:15 Creating service 'pgsql-cluster-1' for pgsql-cluster-junk.cluster-c2xf8ljleb1r.us-west-2.rds.amazonaws.com
2022/09/16 16:56:15 Seems like we are running in a Kubernetes cluster!!
2022/09/16 16:56:15 New resource version of the DB cluster pgsql-cluster-1 is 736737428
2022/09/16 16:56:15 Creation of DB cluster pgsql-cluster-1 done
2022/09/16 16:56:15 Seems like we are running in a Kubernetes cluster!!
2022/09/16 16:56:16 Found node with ID: i-04b6432d9ebeb2e3b in region us-west-2
2022/09/16 16:56:16 Taking subnets from node i-04b6432d9ebeb2e3b
2022/09/16 16:56:16 trying to describe instance
2022/09/16 16:56:19 trying to get subnets
2022/09/16 16:56:19 Security groupid:  sg-0f3ce7d47d2175a68
2022/09/16 16:56:19 Found VPC vpc-0fdfd77cda33f681c will search for subnet in that VPC
2022/09/16 16:56:19 Found the follwing subnets:
2022/09/16 16:56:19 subnet-0312bd982d89f088e
2022/09/16 16:56:19 subnet-0791eebb4d3e05f81
2022/09/16 16:56:19 subnet-0d97c4fef202c5aae
2022/09/16 16:56:19 subnet-07982cc3f1c41d778
2022/09/16 16:56:19 subnet-067c1fbeb25342eb7
2022/09/16 16:56:19 subnet-091d17ae01b066f88
2022/09/16 16:56:19 trying to get security groups
2022/09/16 16:56:19 Taking security groups from node i-04b6432d9ebeb2e3b
2022/09/16 16:56:19 trying to describe instance
2022/09/16 16:56:19 got instance response
2022/09/16 16:56:19 Security groupid:  sg-0f3ce7d47d2175a68
2022/09/16 16:56:19 Found the follwing security groups:
2022/09/16 16:56:19 sg-0f3ce7d47d2175a68
2022/09/16 16:56:19 Seems like we are running in a Kubernetes cluster!!
2022/09/16 16:56:19 Trying to find db cluster instance pgsql-cluster-junk to update
2022/09/16 16:56:20 DB cluster instance pgsql-cluster-junk found trying to update it
2022/09/16 16:56:20 Updating DB cluster failed: ModifyDBCluster:operation error RDS: ModifyDBCluster, https response error StatusCode: 400, RequestID: 98507bbf-ae02-4ab7-87c7-e4617f9edf5a, InvalidDBClusterStateFault: Cannot modify engine version without a healthy primary instance in DB cluster: pgsql-cluster-junk
2022/09/16 16:56:20 Updating db cluster: UpdateDBCluster:ModifyDBCluster: operation error RDS: ModifyDBCluster, https response error StatusCode: 400, RequestID: 98507bbf-ae02-4ab7-87c7-e4617f9edf5a, InvalidDBClusterStateFault: Cannot modify engine version without a healthy primary instance in DB cluster: pgsql-cluster-junk
2022/09/16 16:56:20 db cluster update failed: ModifyDBCluster: operation error RDS: ModifyDBCluster, https response error StatusCode: 400, RequestID: 98507bbf-ae02-4ab7-87c7-e4617f9edf5a, InvalidDBClusterStateFault: Cannot modify engine version without a healthy primary instance in DB cluster: pgsql-cluster-junk
2022/09/16 16:56:20 New resource version of the DB cluster pgsql-cluster-1 is 736737428
```

**Comment by amazzalel-habib** [comment]
> so created and deleting the database cluster object works, with no instances inside as expected with the CRUD, but there is a ModifyCluster happening right after as decribed here when the cluster is still in the creating state.
> 
> maybe we should hold off on ModifyDBCluster calls until there is an healthy instance and the cluster State is Available? what are your thoughts @amazzalel-habib
> 
> ```
> 2022/09/16 16:55:04 Seems like we are running in a Kubernetes cluster!!
> 2022/09/16 16:55:04 services "pgsql-cluster-1" not found
> 2022/09/16 16:55:04 delete of service pgsql-cluster-1 failed in namespace rds-operator: services "pgsql-cluster-1" not found
> 2022/09/16 16:55:04 Deletion of db cluster pgsql-cluster-1 done
> 2022/09/16 16:55:23 New resource version of the DB cluster pgsql-cluster-1 is 736737428
> 2022/09/16 16:55:23 trying to get kubectl
> 2022/09/16 16:55:23 Seems like we are running in a Kubernetes cluster!!
> 2022/09/16 16:55:23 Found node with ID: i-04b6432d9ebeb2e3b in region us-west-2
> 2022/09/16 16:55:24 Taking subnets from node i-04b6432d9ebeb2e3b
> 2022/09/16 16:55:24 trying to describe instance
> 2022/09/16 16:55:27 trying to get subnets
> 2022/09/16 16:55:27 Security groupid:  sg-0f3ce7d47d2175a68
> 2022/09/16 16:55:27 Found VPC vpc-0fdfd77cda33f681c will search for subnet in that VPC
> 2022/09/16 16:55:27 Found the follwing subnets:
> 2022/09/16 16:55:27 subnet-0312bd982d89f088e
> 2022/09/16 16:55:27 subnet-0791eebb4d3e05f81
> 2022/09/16 16:55:27 subnet-0d97c4fef202c5aae
> 2022/09/16 16:55:27 subnet-07982cc3f1c41d778
> 2022/09/16 16:55:27 subnet-067c1fbeb25342eb7
> 2022/09/16 16:55:27 subnet-091d17ae01b066f88
> 2022/09/16 16:55:27 trying to get security groups
> 2022/09/16 16:55:27 Taking security groups from node i-04b6432d9ebeb2e3b
> 2022/09/16 16:55:27 trying to describe instance
> 2022/09/16 16:55:27 got instance response
> 2022/09/16 16:55:27 Security groupid:  sg-0f3ce7d47d2175a68
> 2022/09/16 16:55:27 Found the follwing security groups:
> 2022/09/16 16:55:27 sg-0f3ce7d47d2175a68
> 2022/09/16 16:55:27 Trying to find the correct subnets
> 2022/09/16 16:55:28 Subnets: [subnet-0312bd982d89f088e subnet-0791eebb4d3e05f81 subnet-0d97c4fef202c5aae subnet-07982cc3f1c41d778 subnet-067c1fbeb25342eb7 subnet-091d17ae01b066f88]
> 2022/09/16 16:55:28 Moving on seems like db-subnetgroup-vpc-0fdfd77cda33f681c exsits
> 2022/09/16 16:55:28 getting secret: Name: rds-credentials Key: password
> 2022/09/16 16:55:28 Seems like we are running in a Kubernetes cluster!!
> 2022/09/16 16:55:28 WARNING: Not Adding annotation KV to tags: kubectl.kubernetes.io/last-applied-configuration {"apiVersion":"k8s-rds.io/v1","kind":"DBCluster","metadata":{"annotations":{},"name":"pgsql-cluster-1","namespace":"rds-operator"},"spec":{"BackupRetentionPeriod":1,"DBClusterIdentifier":"pgsql-cluster-junk","DeletionProtection":false,"Engine":"aurora-postgresql","EngineVersion":"14.3","MasterUserPassword":{"key":"password","name":"rds-credentials"},"MasterUsername":"postgres","MultiAZ":false,"Port":5432,"Provider":"aws","ServerlessV2ScalingConfiguration":{"MaxCapacity":11,"MinCapacity":1},"SkipFinalSnapshot":true,"Tags":"key=value,key1=value1"}}
> 2022/09/16 16:55:28 Trying to find db cluster pgsql-cluster-junk
> 2022/09/16 16:55:28 DB Cluster instance 0xc00081a660 not found trying to create it
> 2022/09/16 16:55:30 Waiting for db cluster instance with ID pgsql-cluster-junk  to become available
> 2022/09/16 16:56:15 DB cluster pgsql-cluster-junk is now available
> 2022/09/16 16:56:15 Creating service 'pgsql-cluster-1' for pgsql-cluster-junk.cluster-c2xf8ljleb1r.us-west-2.rds.amazonaws.com
> 2022/09/16 16:56:15 Seems like we are running in a Kubernetes cluster!!
> 2022/09/16 16:56:15 New resource version of the DB cluster pgsql-cluster-1 is 736737428
> 2022/09/16 16:56:15 Creation of DB cluster pgsql-cluster-1 done
> 2022/09/16 16:56:15 Seems like we are running in a Kubernetes cluster!!
> 2022/09/16 16:56:16 Found node with ID: i-04b6432d9ebeb2e3b in region us-west-2
> 2022/09/16 16:56:16 Taking subnets from node i-04b6432d9ebeb2e3b
> 2022/09/16 16:56:16 trying to describe instance
> 2022/09/16 16:56:19 trying to get subnets
> 2022/09/16 16:56:19 Security groupid:  sg-0f3ce7d47d2175a68
> 2022/09/16 16:56:19 Found VPC vpc-0fdfd77cda33f681c will search for subnet in that VPC
> 2022/09/16 16:56:19 Found the follwing subnets:
> 2022/09/16 16:56:19 subnet-0312bd982d89f088e
> 2022/09/16 16:56:19 subnet-0791eebb4d3e05f81
> 2022/09/16 16:56:19 subnet-0d97c4fef202c5aae
> 2022/09/16 16:56:19 subnet-07982cc3f1c41d778
> 2022/09/16 16:56:19 subnet-067c1fbeb25342eb7
> 2022/09/16 16:56:19 subnet-091d17ae01b066f88
> 2022/09/16 16:56:19 trying to get security groups
> 2022/09/16 16:56:19 Taking security groups from node i-04b6432d9ebeb2e3b
> 2022/09/16 16:56:19 trying to describe instance
> 2022/09/16 16:56:19 got instance response
> 2022/09/16 16:56:19 Security groupid:  sg-0f3ce7d47d2175a68
> 2022/09/16 16:56:19 Found the follwing security groups:
> 2022/09/16 16:56:19 sg-0f3ce7d47d2175a68
> 2022/09/16 16:56:19 Seems like we are running in a Kubernetes cluster!!
> 2022/09/16 16:56:19 Trying to find db cluster instance pgsql-cluster-junk to update
> 2022/09/16 16:56:20 DB cluster instance pgsql-cluster-junk found trying to update it
> 2022/09/16 16:56:20 Updating DB cluster failed: ModifyDBCluster:operation error RDS: ModifyDBCluster, https response error StatusCode: 400, RequestID: 98507bbf-ae02-4ab7-87c7-e4617f9edf5a, InvalidDBClusterStateFault: Cannot modify engine version without a healthy primary instance in DB cluster: pgsql-cluster-junk
> 2022/09/16 16:56:20 Updating db cluster: UpdateDBCluster:ModifyDBCluster: operation error RDS: ModifyDBCluster, https response error StatusCode: 400, RequestID: 98507bbf-ae02-4ab7-87c7-e4617f9edf5a, InvalidDBClusterStateFault: Cannot modify engine version without a healthy primary instance in DB cluster: pgsql-cluster-junk
> 2022/09/16 16:56:20 db cluster update failed: ModifyDBCluster: operation error RDS: ModifyDBCluster, https response error StatusCode: 400, RequestID: 98507bbf-ae02-4ab7-87c7-e4617f9edf5a, InvalidDBClusterStateFault: Cannot modify engine version without a healthy primary instance in DB cluster: pgsql-cluster-junk
> 2022/09/16 16:56:20 New resource version of the DB cluster pgsql-cluster-1 is 736737428
> ```

that's weird, I'll check it and get back to you

**Comment by liskl** [comment]
seeing an error on build

```
#0 23.21 rds/rds_provider.go:449:27: Error return value is not checked (errcheck)
#0 23.21                                        waitForDBAvailability(ctx, rdsdb.DBClusterMembers[0].DBInstanceIdentifier, rdsCli)
#0 23.21                                                             ^
#0 23.28 make: *** [Makefile:19: lint] Error 1
```

**Comment by amazzalel-habib** [comment]
> seeing an error on build
> 
> ```
> #0 23.21 rds/rds_provider.go:449:27: Error return value is not checked (errcheck)
> #0 23.21                                        waitForDBAvailability(ctx, rdsdb.DBClusterMembers[0].DBInstanceIdentifier, rdsCli)
> #0 23.21                                                             ^
> #0 23.28 make: *** [Makefile:19: lint] Error 1
> ```

Fixed

**Comment by liskl** [comment]
the deletion of a cluster using only the DBCluster object kubectl delete dbcluster.k8s-rds.io pgsql-cluster-1 resulted in the deletion of the instance but failed to finally delete the cluster itself

**Review by liskl — APPROVED** [review]
looks good.

**Pull request merged**
